apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: gm-1
  namespace: silicom
spec:
  namespace: silicom
  nodeSelector:
    sts.silicom.com/config: "gm-1"
  mode: T-GM.8275.1
  interfaces:
    - ethName: enp138s0f2
      holdoff: 500
      synce: 1
      mode: Master
      ethPort: 0
    - ethName: enp138s0f0
      synce: 1
      holdoff: 500
      mode: Master
      ethPort: 1
