apiVersion: v1
kind: Pod
metadata:
  name: cyclictest-du4ldc1
  namespace: cyclictest
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  runtimeClassName: performance-ran-du-ldc1-smci04-profile0
  restartPolicy: Never
  containers:
  - name: container-perf-tools
    image: altiostar-registry.cars.lab:5000/cyclictest
    imagePullPolicy: Always
    resources:
      # NOTE: Requests and limits MUST be identical for the Pod to be assigned to the QoS Guaranteed class
      requests:
        memory: "200Mi"
        cpu: "50"
      limits:
        memory: "200Mi"
        cpu: "50"
    env:
    - name: GIT_URL
      value: "false"
    - name: tool
      value: "cyclictest"
    - name: rt_priority
      value: "95"
    - name: DURATION
      value: "24h"
    - name: INTERVAL
      value: "100"
      # To report SMI include flag here
      #value: "100 -smi"
    # # Following setting not required in OCP4.6+
    # - name: DISABLE_CPU_BALANCE
    #   value: "y"
    # DISABLE_CPU_BALANCE requires privileged=true
    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    volumeMounts:
    - mountPath: /dev/cpu_dma_latency
      name: cstate
      readOnly: true
  volumes:
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  nodeSelector:
    node-role.kubernetes.io/ran-du-ldc1-smci04: ""
# Use NodeName to select a node to execute cyclic test
  nodeName: du4-ldc1