#oc label node du4-ldc1 machineconfiguration.openshift.io/role=worker-cnf
#oc label node du3-ldc1 machineconfiguration.openshift.io/role=worker-cnf
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  annotations:
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: worker-cnf
  name: 50-disable-chronyd
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
      - contents: |
          [Unit]
          Description=NTP client/server
          Documentation=man:chronyd(8) man:chrony.conf(5)
          After=ntpdate.service sntp.service ntpd.service
          Conflicts=ntpd.service systemd-timesyncd.service
          ConditionCapability=CAP_SYS_TIME
          [Service]
          Type=forking
          PIDFile=/run/chrony/chronyd.pid
          EnvironmentFile=-/etc/sysconfig/chronyd
          ExecStart=/usr/sbin/chronyd $OPTIONS
          ExecStartPost=/usr/libexec/chrony-helper update-daemon
          PrivateTmp=yes
          ProtectHome=yes
          ProtectSystem=full
          [Install]
          WantedBy=multi-user.target
        enabled: false
        name: chronyd.service
