apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  generation: 1
  labels:
    topology.kubernetes.io/zone: ldc1
  name: ldc1-ptp-smci02
  namespace: openshift-ptp
spec:
  profile:
  - interface: enp138s0f2
    name: ldc1-ptp-smci02-sil
    phc2sysOpts: -a -r -n 24
    ptp4lConf: |
      [global]
      #
      # Default Data Set
      #
      twoStepFlag 1
      slaveOnly 1
      priority1 128
      priority2 128
      clockClass 248
      clockAccuracy 0xFE
      offsetScaledLogVariance 0xFFFF
      free_running 0
      freq_est_interval 1
      dscp_event 0
      dscp_general 0
      #dataset_comparison G.8275.x
      #G.8275.defaultDS.localPriority 128
      #G.8275.portDS.localPriority 128
      #
      # Port Data Set
      #
      logAnnounceInterval -3
      logSyncInterval -4
      logMinDelayReqInterval -4
      logMinPdelayReqInterval 0
      announceReceiptTimeout 3
      syncReceiptTimeout 100
      delayAsymmetry 0
      #update 30-Nov per Pasi recommendations:
      fault_reset_interval -8
      neighborPropDelayThresh 20000000
      #
      # Run time options
      #
      assume_two_step 0
      logging_level 6
      path_trace_enabled 0
      follow_up_info 0
      hybrid_e2e 0
      #update 30-Nov per Intel recommendations:
      tx_timestamp_timeout 50
      use_syslog 1
      verbose 1
      #summary_interval 0
      kernel_leap 1
      check_fup_sync 0
      #
      # Servo Options
      #
      pi_proportional_const 0.0
      pi_integral_const 0.0
      pi_proportional_scale 0.0
      pi_proportional_exponent -0.3
      pi_proportional_norm_max 1
      pi_integral_scale 0.5
      pi_integral_exponent 1
      pi_integral_norm_max 0.3
      step_threshold 0.0
      first_step_threshold 0.00002
      max_frequency 900000000
      clock_servo pi
      sanity_freq_limit 200000000
      ntpshm_segment 0
      #
      # Transport Options
      #
      transportSpecific 0x0
      ptp_dst_mac 01:80:C2:00:00:0E
      p2p_dst_mac 01:80:C2:00:00:0E
      udp_ttl 1
      udp6_scope 0x0E
      uds_address /var/run/ptp4l
      #
      # Default Interface Options
      #
      #    clock_type OC
      network_transport L2
      delay_mechanism E2E
      time_stamping hardware
      tsproc_mode filter
      delay_filter moving_median
      delay_filter_length 50
      egressLatency 0
      ingressLatency 0
      boundary_clock_jbod 0
      #
      # Clock Description
      #
      productDescription ;;
      revisionData ;;
      manufacturerIdentity 00:00:00
      userDescription ;
      timeSource 0xA0
      domainNumber 24
      #
      # INTEL HACK E810
      #
      #sanity_freq_limit 0
      #step_threshold 30.0
    ptp4lOpts: -2 --summary_interval -4 -m -s -H
  recommend:
  - match:
    - nodeLabel: ran.openshift.io/ldc1-ptp-smci02
    priority: 1
    profile: ldc1-ptp-smci02-sil
